# Generated by Django 3.2.10 on 2022-07-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(default='', max_length=100),
        ),
    ]
