# Generated by Django 3.2.10 on 2022-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('男', 'M'), ('女', 'F')], max_length=100, null=True),
        ),
    ]
