# Generated by Django 3.2.10 on 2022-07-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('女', 'F')], max_length=100, null=True),
        ),
    ]
