# Generated by Django 3.2.10 on 2022-07-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20220723_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
